# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NewCli < Formula
  desc ""
  homepage "https://https://github.com/selinafinance-poc/new-cli"
  version "0.3"

  on_macos do
    url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.3/new-cli_0.3_darwin_all.tar.gz"
    sha256 "8d796f2a09d1b5a6bba5aab337f4a2d4893c5e360b01526bc6a32ca0890e7c50"

    def install
      bin.install "new-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.3/new-cli_0.3_linux_arm64.tar.gz"
      sha256 "7a9f3ace93e083c72774bf70b7db3fe7d0bad457d37deb689fe5565879c0399e"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.3/new-cli_0.3_linux_amd64.tar.gz"
      sha256 "009d4a40ffba8fefb4b011bb2ec5967fc9b1c5742e19543191c696b267195d22"

      def install
        bin.install "new-cli"
      end
    end
  end
end
