# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NewCli < Formula
  desc ""
  homepage "https://https://github.com/selinafinance-poc/new-cli"
  version "0.4"

  on_macos do
    url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.4/new-cli_0.4_darwin_all.tar.gz"
    sha256 "b3ee54c826f7d561520be756f53335ee1d433ef82f209926afcf4b507338130c"

    def install
      bin.install "new-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.4/new-cli_0.4_linux_arm64.tar.gz"
      sha256 "4619fef3aad68fffc9d89aa1a8cc73796b7170fa2512f6ddb97534b076e579bc"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.4/new-cli_0.4_linux_amd64.tar.gz"
      sha256 "4b9c5decfadb8edc5cedf0c56a67ca69f866512a86d7af1e5770953cdcaffd76"

      def install
        bin.install "new-cli"
      end
    end
  end
end
