# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class JxSelina < Formula
  desc ""
  homepage "git@github.com:selinafinance-devops/jx-selina"
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/Selina-Finance/jx-selina/releases/download/v0.2.4/jx-selina-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "62dcf4e9932017ef88b84f1f7ce54ce99866192a807f64d43d40fd9cf07f4154"

      def install
        bin.install "jx-selina"
      end
    end
    on_arm do
      url "https://github.com/Selina-Finance/jx-selina/releases/download/v0.2.4/jx-selina-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5a54d8fce72b5370ddeb373fe41428f9094c0a8cb372d46b51b2ed686fb591ce"

      def install
        bin.install "jx-selina"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Selina-Finance/jx-selina/releases/download/v0.2.4/jx-selina-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "af32017b7efcad49d5900c83774d4ddd074712ce2e78dc2f2703ba2ccf723700"

        def install
          bin.install "jx-selina"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Selina-Finance/jx-selina/releases/download/v0.2.4/jx-selina-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "c46286e4ceeeb2c9d609b971b7ab24dffca25a464d3c56306c18d249c2d24186"

        def install
          bin.install "jx-selina"
        end
      end
    end
  end
end
