# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class NewCli < Formula
  desc ""
  homepage "https://https://github.com/selinafinance-poc/new-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "604b8fe1499d38d0ff97403c532ddc0a5da82a6d9c762519f2d18d87726736c5"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "df852bd20e64369f7a1ff99c112ad413454bd6cab8e6144a164e21b9b24895af"

      def install
        bin.install "new-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7a32a885a56716bb35db8b8e58b249bcc3540a6d605b6fa63fbec035511236f6"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3f24966ea14db61fe25bd7d167e3107826d611725041402655a90a191a7f7422"

      def install
        bin.install "new-cli"
      end
    end
  end
end
