# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class NewCli < Formula
  desc ""
  homepage "https://https://github.com/selinafinance-poc/new-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.2/new-cli-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "41cd2a7845a5faf5b35c67f6d1a40fe14837de96608abb743b2bbfa257869327"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.2/new-cli-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c131206477d63f7d818483013e5ca0daf6be47f66c816dc354d9f5c8a78cdda4"

      def install
        bin.install "new-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.2/new-cli-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9d745d4d81c3a91d27635a48198de781e8c83595f4a2c95cc52d2cfc090500ee"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.2/new-cli-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3b5aec096867b3eb1b8377023b35a72e3df0ed51b4160d123ec30db038acd295"

      def install
        bin.install "new-cli"
      end
    end
  end
end
