# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class NewCli < Formula
  desc ""
  homepage "https://https://github.com/selinafinance-poc/new-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "61e08caff4217f1a60c0833cb0a65dd146853828df727605e5019e089825ab02"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-darwin-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "50756d99bcce3653c71bad109d92888d1c6bac101f14caf6ead9eddb14dd7ee3"

      def install
        bin.install "new-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4d68c5ead9610c7eb2e7c80c5a2df5bbe6c965f93bede8aeb9d52b1ebdce0a78"

      def install
        bin.install "new-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/selinafinance-poc/new-cli/releases/download/v0.0.1/new-cli-linux-amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "23fe60607ac415de7e92b8833a558b87356938830acbd095217d7b2a09628d4c"

      def install
        bin.install "new-cli"
      end
    end
  end
end
